---
title: "References"
layout: default
---

```{r, echo=FALSE}
# How to create: %s/\n/\r\r/gc in vim
```


# Bibliography

Agresti, A. (2007). An introduction to categorical data analysis. Wiley-Interscience.

Avram, S., Figari, F., Leventi, C., Levy, H., Navicke, J., Matsaganis, M., … Sutherland, H. (2012). The distributional effects of fiscal consolidation in 9 EU countries.

Ballas, D., Clarke, G. P., Dorling, D., Eyre, H., Thomas, B., & Rossiter, D. (2005). SimBritain: a spatial microsimulation approach to population dynamics. Population, Space and Place, 11(1), 13–34. doi:10.1002/psp.351

Barthélemy, J. (2014). A parallelized micro-simulation platform for population and mobility behaviour-Application to Belgium. University de Namur.

Barthelemy, J., & Toint, P. L. (2012). Synthetic Population Generation Without a Sample. Transportation Science, 47(2), 266–279. doi:10.1287/trsc.1120.0408

Beezer, R. A. (2008). A first course in linear algebra. Puget Sound: Congruent Press.

Bell, P. (1999). Weighting and Standard Error Estimation for ABS Household Surveys (Paper prepared for ABS Methodology Advisory Committee).

Bierlaire, M. (1991). Evaluation de la demande en trafic: quelques méthodes de distribution. In Annales de la Société Scientifique de Bruxelles (Vol. 105, pp. 17–66).

Blumer, A., Ehrenfeucht, A., Haussler, D., & Warmuth, M. K. (1987). Occam’s razor. Information Processing Letters, 24(6), 377–380.

Boyd, S., & Vandenberghe, L. (2009). Convex optimization. Cambridge university press.

Chai, T., & Draxler, R. R. R. (2014). Root mean square error (RMSE) or mean absolute error (MAE)? – Arguments against avoiding RMSE in the literature. Geoscientific Model Development, 7(3), 1247–1250. doi:10.5194/gmd-7-1247-2014

Clarke, M., & Holm, E. (1987). Microsimulation methods in spatial analysis and planning. Geografiska Annaler. Series B. Human Geography, 69(2), 145–164. Retrieved from http://www.jstor.org/stable/10.2307/490448

Cleave, N., Brown, P. J., & Payne, C. D. (1995). Evaluation of Methods for Ecological Inference. Journal of the Royal Statistical Society. Series A, 158(1), pp. 55–72. Retrieved from http://www.jstor.org/stable/2983403

De Agostini, P., Hills, J., & Sutherland, H. (2014). Were we really all in it together? The distributional effects of the UK Coalition government’s tax-benefit policy changes. Retrieved from http://sticerd.lse.ac.uk/dps/case/spcc/wp10.pdf

Deming, W., & Stephan, F. F. (1940). On a least squares adjustment of a sampled frequency table when the expected marginal totals are known. The Annals of Mathematical Statistics. Retrieved from http://www.jstor.org/stable/10.2307/2235722

Edwards, K., & Clarke, G. (2013). SimObesity: Combinatorial Optimisation (Deterministic) Model. Spatial Microsimulation: A Reference Guide for Users, 69–85. doi:10.1007/978-94-007-4623-7

Edwards, K. L., Clarke, G. P., Thomas, J., & Forman, D. (2010). Internal and External Validation of Spatial Microsimulation Models: Small Area Estimates of Adult Obesity. Applied Spatial Analysis and Policy, 4(4), 281–300. doi:10.1007/s12061-010-9056-2

Feynman’s, R. (1995). The making of a scientist. Learning, 23, 2.

Fienberg, S. E., & Rinaldo, A. (2007). Three centuries of categorical data analysis: Log-linear models and maximum likelihood estimation. Journal of Statistical Planning and Inference, 137(11), 3430–3445. doi:10.1016/j.jspi.2007.03.022

Gaber, J. (2007). Simulating Planning: SimCity as a Pedagogical Tool. Journal of Planning Education and Research, 27(2), 113–121. doi:10.1177/0739456X07305791

Grimm, V., & Railsback, S. F. (2011). Agent-based and individual-based modeling: a practical introduction. Princeton University Press Princeton, NJ.

Harland, K. (2013). Microsimulation model user guide: flexible modelling framework (No. 0613). National Centre for Research Methods (Vol. 1306). Leeds: NCRM. doi:http://eprints.ncrm.ac.uk/3177/2/microsimulation_model.pdf

Harland, K., Heppenstall, A., Smith, D., & Birkin, M. (2012). Creating Realistic Synthetic Populations at Varying Spatial Scales: A Comparative Critique of Population Synthesis Techniques. Journal of Artificial Societies and Social Simulation, 15(1), 1. Retrieved from http://jasss.soc.surrey.ac.uk/15/1/1.html

Hornik, K. (2012). Are There Too Many R Packages? Austrian Journal of Statistics, 41(1), 59–66.

Ince, D. C., Hatton, L., & Graham-Cumming, J. (2012). The case for open computer programs. Nature, 482(7386), 485–8. doi:10.1038/nature10836

Jones, O., Maillardet, R., & Robinson, A. (2014). Introduction to scientific programming and simulation using R (2nd ed.). Chapman and Hall/CRC.

Kabacoff, R. (2011). R in Action. Manning Publications Co.

Knoblauch, K., & Maloney, L. T. (2012). Modeling psychophysical data in R (Vol. 32). Springer. Retrieved from http://mpdir.r-forge.r-project.org/book/Front.pdf

Lenormand, M, & Deffuant, G. (2015). Generating a synthetic population of individuals in households: Sample-free vs sample-based methods. Journal of Artificial Societies and Social Simulation, 16(4):12. Retrieved from http://arxiv.org/pdf/1208.6403v2.pdf

Lovelace, R. (2014). Introducing spatial microsimulation with R: a practical. National Centre for Research Methods, 08(14). Retrieved from http://eprints.ncrm.ac.uk/3348/

Lovelace, R., & Ballas, D. (2013). “Truncate, replicate, sample”: A method for creating integer weights for spatial microsimulation. Computers, Environment and Urban Systems, 41, 1–11. doi:10.1016/j.compenvurbsys.2013.03.004

Lovelace, R., & Cheshire, J. (2014). Introduction to visualising spatial data in R. National Centre for Research Methods Working Papers, 14(03). Retrieved from https://github.com/Robinlovelace/Creating-maps-in-R

Lucas, K. (2012). Transport and social exclusion: Where are we now? Transport Policy, 20, 105–113. doi:10.1016/j.tranpol.2012.01.013

McNutt, M. (2014). Journals unite for reproducibility. Science, 346(6210), 679. doi:10.1126/science.aaa1724

Müller, K., & Axhausen, K. (2010). Population synthesis for microsimulation: State of the art. Population (English Edition). Retrieved from http://www.strc.ch/conferences/2010/Mueller.pdf

Norman, P. (1999). Putting Iterative Proportional Fitting (IPF) on the Researcher’s Desk. Retrieved from http://eprints.whiterose.ac.uk/5029/1/99-3.pdf

Peng, R. D., Dominici, F., & Zeger, S. L. (2006). Reproducible epidemiologic research. American Journal of Epidemiology, 163(9), 783–9. doi:10.1093/aje/kwj093

Popper, K. (1959). The Logic of scientific discovery. Hutchinson. Retrieved from http://books.google.com/books?id=MdvaSAAACAAJ&pgis=1

Powell, D. a., Jacob, C. J., & Chapman, B. J. (2011). Enhancing food safety culture to reduce rates of foodborne illness. Food Control, 22(6), 817–822. doi:10.1016/j.foodcont.2010.12.009

Pritchard, D. R., & Miller, E. J. (2012). Advances in population synthesis: fitting many attributes per agent and fitting to household and person margins simultaneously. Transportation, 39(3), 685–704. doi:10.1007/s11116-011-9367-4

Rahman, A. (2009). Small Area Estimation Through Spatial Microsimulation Models. In 2nd International Microsimulation Association Conference. Ottawa and Canada.

Rao, J. N. K. (2003). Small area estimation (Vol. 331). John Wiley & Sons.

Rey, S. J. (2014). Open regional science. The Annals of Regional Science, 52(3), 825–837. doi:10.1007/s00168-014-0611-7

Singh, A., & Mohl, C. (1996). Understanding calibration estimators in survey sampling. Survey Methodology, 22, 107–115.

Smith, A., Martin, D., & Cockings, S. (2014). Spatio-Temporal Population Modelling for Enhanced Assessment of Urban Exposure to Flood Risk. Applied Spatial Analysis and Policy. doi:10.1007/s12061-014-9110-6

Sutherland, H., & Figari, F. (2013). EUROMOD: the European Union tax-benefit microsimulation model. International Journal of Microsimulation, 6(1), 4–26.

Tanton, R., Vidyattama, Y., Nepal, B., & McNamara, J. (2011a). Small area estimation using a reweighting algorithm. Journal of the Royal Statistical Society. Series A, 174(4), 931–951. doi:10.1111/j.1467-985X.2011.00690.x

Tanton, R., Vidyattama, Y., Nepal, B., & McNamara, J. (2011b). Small area estimation using a reweighting algorithm. Journal of the Royal Statistical Society: Series A (Statistics in Society), 174(4), 931–951. doi:10.1111/j.1467-985X.2011.00690.x

Thiele, J. (2014). R Marries NetLogo: Introduction to the RNetLogo Package. Journal of Statistical, 58(2), 1–41. Retrieved from http://www.jstatsoft.org/v58/i02/paper

Thiele, J. C., Kurth, W., & Grimm, V. (2012). Agent-Based Modelling: Tools for Linking NetLogo And R . Journal of Artificial Societies and Social Simulation, 15(3), 8. Retrieved from http://jasss.soc.surrey.ac.uk/15/3/8.html

Thiele, J., Kurth, W., & Grimm, V. (2014). Facilitating Parameter Estimation and Sensitivity Analysis of Agent-Based Models: A Cookbook Using NetLogo and’R'. Journal of Artificial Societies and …, 17(11). Retrieved from https://ideas.repec.org/a/jas/jasssj/2013-150-2.html

Tomintz, M. N. M. N. N., Clarke, G. P., & Rigby, J. E. J. E. E. (2008). The geography of smoking in Leeds: estimating individual smoking rates and the implications for the location of stop smoking services. Area, 40(3), 341–353. Retrieved from http://onlinelibrary.wiley.com/doi/10.1111/j.1475-4762.2008.00837.x/full

Venables, W. W. N., Smith, D. M. D. M., Team, R. D. C., & Others. (2014). An introduction to R, 1. Retrieved from http://folk.uio.no/bernde/pub/Statistics.pdf http://cran.ma.imperial.ac.uk/doc/manuals/r-devel/R-intro.pdf

Voas, D., & Williamson, P. (2001). Evaluating Goodness-of-Fit Measures for Synthetic Microdata. Geographical and Environmental Modelling, 5(2), 177–200. doi:10.1080/13615930120086078

Wheelock, J., & Oughton, E. (1996). The household as a focus for research. Journal of Economic Issues, 143–159.

Wickham, H. (2014a). Advanced R. CRC Press. Retrieved from http://www.crcpress.com/product/isbn/9781466586963

Wickham, H. (2014b). Tidy data. The Journal of Statistical Software, 14(5). Retrieved from http://www.jstatsoft.org/v59/i10

Williamson, P. (2007). CO Instruction Manual: Working Paper 2007/1 (v. 07.06.25). Population (English Edition) (Vol. 1).

Zubizarreta, J. R. (2012). Using mixed integer programming for matching in an observational study of kidney failure after surgery. Journal of the American Statistical Association, 107(500), 1360–1371.



