---
title: "What is spatial microsimulation?"
layout: default
---

# What is spatial microsimulation?

Spatial microsimulation is a
statistical technique for allocating individuals from a survey dataset
to administrative zones, based on shared variables between the areal and
individual level data.
As with many new and infrequently used phrases, this
understanding is not shared by everyone. The meaning of spatial
microsimulation varies depending on context and who you ask. To an
economist, spatial microsimulation is likely to imply
modelling some kind of temporal process such as how individual agents in
different areas respond to changes in prices or policies. To a transport
planner, the term may imply simulating the precise movements of vehicles on
the transport network. To your next door neighbour it may mean you have
started speaking gobbledygook! Hence the need to consider what spatial
microsimulation is, and what it is not, at the outset.

## Terminology

Delving a little into the etymology and history of the term reveals the
reasons behind this duplicity of meaning and highlights the importance
of terminology. Rarely will you be understood saying
“I use *spatial microsimulation*” in everyday life. Usually it
is important to add context. Below are a few hypothetical situations and
suggested responses.

-   When talking to a colleague, a transport modeller: “spatial
    microsimulation, also known as population synthesis...”

-   Speaking to agent based modellers: “we use spatial microsimulation
    to simulate the characteristics of geo-referenced agents...”

-   Communicating with undergraduates who are unlikely to have come
    across the term or its analogies. “I do spatial microsimulation, a
    way of generating individual-level data for small areas...”

-   Chatting casually in the pub or coffee shop: “I’m using a technique
    called spatial microsimulation to model people...”.

The above examples illustrate potential for
confusion: care needs to be taken to use terminology each audience understands. The transport modeller, for example, may
already know that the term 'population synthesis' means creating an individual-level
dataset of real areas, whereas more basic terms need to be used when communicating
the method to policy makers. All this links back to the importance
of transparency and reproducibility of method discussed in the previous chapter:
avoid implying spatial microsimulation is something it is not.

Faced with uncomprehending stares when describing the method, some may
be tempted to ‘blind them with science’, relying on
sophisticated-sounding jargon, for example by saying: “we use simulated
annealing in our integerised spatial microsimulation model”. Such
wording obscures meaning (how many people in the room will understand
‘integerised’, let alone ‘simulated annealing’) and makes the process
inaccessible. Although much jargon is used in the spatial
microsimulation literature and in this book, care must be taken to ensure
that people understand what you are saying.

This raises the question, why use the term spatial microsimulation at
all, if it is understood by so few people? The answer to this is that
spatial microsimulation, defined clearly at the outset and used
correctly, can concisely describe a technique that would otherwise need
many more words on each use. Try replacing ‘spatial microsimulation’
with ‘a statistical technique to allocate individuals from a survey
dataset to administrative zones’ each time it appears in this book and
the advantages of a simple term should become clear! ‘Population
synthesis’ is perhaps a more accurate term but, transport modelling
aside, the literature already uses ‘spatial microsimulation’. Rather
than create more complexity with *another* piece of jargon, we proceed
with the term favoured by the majority of practitioners.

Why has this situation, in which practitioners of a statistical method
must tread carefully to avoid confusing their audience, come about?
First it’s worth stating that the problem is by no means unique to this
field: imagine the difficulties that Bayesian statisticians must
encounter when speaking of prior and posterior probability distributions
to an uninitiated audience. Let alone describing Gibb’s sampling.

To avoid confusion regarding the terminology used in this book,
a glossary defining much of the jargon relating to spatial microsimulation
is provided at the end. For now, to
help answer what spatial microsimulation is we will look at 
its applications and then at what it is not.

Applications
----------------------------------------

Spatial microsimulation has a wide variety of applications and there
are many areas where the technique has been used.
Some of the main areas of application have
been health, economic policy evaluation and transport. Rather than attempt
to provide a comprehensive account of the range of current and possible
applications, this section describes a single study in each area to exemplify
how spatial microsimulation is used.

### Health applications

An excellent example of the potential practical utility of spatial microsimulation
is a study by Tomintz et al. (2008), which estimated the rate of smoking at the
small area level. Smoking is a classic 'target variable' in spatial microsimulation:
it is reported in a number of individual-level surveys but there is surprisingly
little information about

### Economic policy evaluation

### Transport

What spatial microsimulation is not
-----------------------------------

**Spatial microsimulation is not strictly spatial**

The most surprising feature of spatial microsimulation
is that the method is not strictly *spatial*. The only
reason why the method has developed this name (as opposed to 'small
area population synthesis', for example) is that practitioners tend
to use administrative zones, which represent geographical areas, as the
grouping variable. However, any mutually exclusive grouping variable,
such as age band or number of bedrooms in your house, could
be used. Likewise, geographical location can be used as a *constraint variable*.
In most spatial microsimulation models, the spatial variable is a mutually
exclusive grouping, interchangeable with any such group. Of course, the spatial
microdata, maps and analysis that result from spatial microsimulation are spatial,
it's just that there is nothing inherently spatial about the method used to
generate the spatial microdata.

To be more precise, spatial microsimulation is not *inherently spatial*.
Spatial attributes such as the geographic coordinates of the zones
to which individuals have been allocated and home and work
locations can easily be added to the spatial microdata after they have been
generated. It is the use of geographical variables as the grouping variable that is
critical here and which distinguishes spatial microsimulation from other types
of microsimulation.

**Spatial microsimulation is not agent-based modelling (ABM).**

Spatial microsimulation does involve the creation and analysis of individuals,
but it does not imply any interaction between these individuals. For this, an
agent-based model (ABM) is needed. It would be easy to assume that because
the method contains the word 'simulation', it includes modelling of individual
behaviours over time and space. This is not the case.

Spatial microsimulation as an approach to modelling involves what-if scenarios,
the allocation of individuals to specific zones and, in some cases, a time
step to represent the individuals' evolution over time. Agent based modelling,
by contrast imply some kind of interaction between the individual units.
Spatial microsimulation is closely linked to ABM, however. As described in
Chapter \ref{ABM}, the outputs of spatial microsimulation form an excellent
basis for ABMs.

**Spatial microsimulation does not generate new data**

During spatial microsimulation, apparently new individuals are created and
placed into zones. It would be tempting to think that new information
about the world is somehow
being created. This is not the case: the 'new' individuals are simply repeats
of individuals we already knew about from the individual-level data, albeit
in a different order and in different combinations. If the population of the
study area is greater than the sample size of the input data, many individuals
will have to be 'cloned'. Thus we are not increasing the diversity of the dataset,
simply changing its aggregate-level characteristics.

## Assumptions {#assumptions}

As with any simulation technique, spatial microsimulation is based on
assumptions, some of which are unlikely to hold in all cases. This
does not preclude spatial microsimulation in cases where the assumptions
do not hold: "It is far better to foresee even without
certainty than not to foresee at all", as Henri Poincaré put it
(Barthélemy, 2014).
It is vital, however, that users of spatial microsimulation and
'consumers' of the resulting research understand that the results of spatial
microsimulation are not *real* but a best estimate of the population in a
given area. The danger is that if the assumptions are not understood, incorrect
conclusions will result. It is therefore the duty of researchers using spatial
microsimulation (and other techniques) to clearly state the assumptions on which
the results depend on and the extent to which these assumptions can be expected
to hold in practice. Roughly speaking there are four main assumptions underlying
all spatial microsimulation models:

1. The individual-level microdata are representative of the study area.
2. The target variable is dependent on the constraint variables and their
interactions in a way that is relatively constant over space and time.
3. The relationships between the constraint variables are not spatially dependent.
4. The input microdataset and constraints are sufficiently rich and detailed
to reproduce the full diversity of individuals and areas in the study region.

Obviously the real world is complex and many processes are spatially dependent,
invalidating assumptions 2 and 3. The extent to which the relationships between
variables can be deemed to be constant over space is often
unknown. However, there there are ways of
checking the spatial dependency of
relationships between multiply variables, not least Geographically Weighted Regression
(GWR). In any case, these limitations should be discussed at the outset of spatial
microsimulation research, with reference to the input data. To see how spatial
microsimulation simplifies the real world, the next chapter describes
a hypothetical scenario where 33 inhabitants of an imaginary land
are simulated and allocated to three zones
based on a microdataset of only 5 individuals and two constraint variables.
