---
title: "Introduction to Spatial Microsimulation with R"
author: "Robin Lovelace"
date: "`r Sys.Date()`"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction

- Housekeeping
- About the course and its teachers
- Lectures and practicals
- Getting help

## Housekeeping

- Thanks to the hosts, the JRC

## Spatial Microsimulation with R

Aims:

1. To provide a solid understanding of the method and applications
2. To teach its implementation in R in general terms
3. To provide guidance on next steps

## Objectives:

- Become proficient with R and RStudio for handling data
- Understand some applications where spatial microsimulation is useful
- Realise the limitations of the method
- Know about a range of packages for doing spatial microsimulation with R
- Understand code for generating spatial microdata with **mipfp**
- Have ideas for trying the methods on your own datasets

# About the course and its teachers

## The request to teach at the EU

- Links with much of the research taking place at the JRC
- Big Data
- Modelling
- Social impact assessment
- Scenarios of the future

## The course materials

- Based on our book - digital versions available on-line
- Slides available on-line
- We'll be making small 'code chunks' and scripts available during the course
- Any feedback welcome

## A bit about us

Robin Lovelace

> - Environmental Geographer turned Computational and Transport Geographer
> - Now on 5 year University Academic Fellowship (UAF) in Transport and Big Data at Leeds Institute for Transport Studies (ITS)
> - Creator of many online teaching materials - see [github.com/robinlovelace](https://github.com/Robinlovelace)
> - Creator of the [**stplanr**](https://github.com/ropensci/stplanr) package
> - Lead developer of the [Propensity to Cycle Tool](http://www.pct.bike/) (PCT)

Morgane Dumont

## A bit about you

- Go-around - who you are, interests in the course
- With your neighbour:
    > - Experience with R
    > - Geographical data

- What you hope to get out of the course

# What is spatial microsimulation and its applications

## What is spatial microsimulation?

1. A method
2. An approach

## Applications

- Wide variety of potential applications
- So far main applications have been in health, poverty mapping and transport
- What do you want to use spatial microsimulation for?
- Tomintz et al. (2008). The geography of smoking in Leeds: estimating individual smoking rates and the implications for the location of stop smoking services. Area, 40(3), 341–353. 
- Gleeson (2014)
- My research

# Agriculture

# Tax policy

# Transport

## What's next:

  - The RStudio Graphical User Interface (GUI)
  - Using R
  - Project management
  - GitHub