---
title: "Course information"
author: "Robin Lovelace and Morgane Dumont"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Course overview for Spatial Microsimulation course in Seville, 7^th^ - 9^th^ November.

## Day 1 (9:30 to 17:30 with one hour break)

- Introduction to spatial microsimulation in R
    - Course overview, aims and objectives (RL)
    - Ask if they have special objectives to reach thanks to this course (RL)

- Applications (with an emphasis on EU projects)
    - Agriculture (RL)
    - Transport (MD - I can present the Jojo's microsimulation - 30 min)
    
- Using R and RStudio for spatial microsimulation (RL : all subsections)
    - The RStudio Graphical User Interface (GUI)
    - Project management
    - GitHub

- Create spatial microdata in R 
    - Loading the data (RL)
    - Preparing the data (RL)
    - Reweighting procedures (MD - I can explain the logic behind the reweighting methods and explain how to code it - 1h)
    - simPop (RL - introduction - 20 min)
  
## Day 2

- Applying the methods of IPF and Combinatorial Optimisation
    - Analysis of spatial microdata (RL)
    - Internal and External Validation (MD - 1h)
    - Population synthesis with integerisation (MD - 1h)

- Testing between different models (RL)

- Visualising and analysing spatial micro-data (RL)

- Spatial micro-data for agent-based models (MD - 30 min)

## Day 3
    
- Spatial microsimulation without micro-data
    - Methods (MD - 1h)
    - Quality of the microsimulation (MD - 1h)
    
- Adding the household information
    - Depending on the databases (MD - 30 min)
    - Several studied cases (MD - 1h30)
    
- Adapt the method to the aim of the simulation
    - Choice of data and methods (MD - 30 min)
    - Application to prepared examples or their own data and aims (MD - 2h)

- Conclusion to the course (RL)



