---
title: "Course information"
author: "Robin Lovelace and Morgane Dumont"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Course overview for Spatial Microsimulation course in Seville, 7^th^ - 9^th^ November.

## Day 1 (9:30 to 17:30 with one hour break)

- [Introduction to spatial microsimulation in R](http://robinlovelace.net/spatial-microsim-book/slides/introduction.pdf) (RL 09:30 - 10:30)
    - Course overview, aims and objectives (RL 9:30 - 10:00)
    - Go-round of participants: course aspirations (RL 10:00 - 10:30)

- What is Spatial Microsimulation and its applications (with an emphasis on EU projects) (10:30 - 11:30)
    - Agriculture (RL)
    - Wealth distribution (RL)
    - Transport (MD - 20 min)
    
- [Using R and RStudio](http://rpubs.com/RobinLovelace/146447) for spatial microsimulation (RL 11:30 - 13:00 See book appendix)
    - Project management
    - GitHub
    - The RStudio Graphical User Interface (GUI)
    - Using R

- [Creating spatial microdata in R](http://robinlovelace.net/spatial-microsim-book/slides/spatial-microdata-in-r.html) (MD 14:00 - 17:10)
    - Loading the data
    - Preparing the data 
    - Reweighting procedures
  
## Day 2

- [Applying the methods of IPF and Combinatorial Optimisation](https://github.com/Robinlovelace/spatial-microsim-book/blob/master/slides/Applying-IPF-and-CO.Rmd) (9:30 - 11:15)
    - Internal and External Validation (MD - 45min)
    - Population synthesis with integerisation (MD - 45 min)
    - Introduction to Combinatorial Optimisation (MD - 30 min)

- [simPop](https://github.com/Robinlovelace/spatial-microsim-book/blob/master/slides/simpop-intro.Rmd) (RL 11:30 - 13:00)

- Spatial data with R (14:00 - 16:00)
    - [Spatial data classes](http://rpubs.com/RobinLovelace/217921) (30 min)
    - Practical working on the [Creating-maps-in-R](https://github.com/Robinlovelace/Creating-maps-in-R) (45 min Q & A)
    - [Visualisation](https://github.com/Robinlovelace/Creating-maps-in-R/blob/master/vignettes/vspd-base-shiny.md) (30 min)
    - [Simple features](https://github.com/edzer/sfr) (**sf** package) (15 min if time)

- [Interactive mapping](https://github.com/Robinlovelace/Creating-maps-in-R/blob/master/vignettes/vspd-base-shiny.md) with **tmap**, **leaflet** and **shiny** (if time) (RL 16:00 - 17:00)

- Spatial micro-data for agent-based models (MD 17:00 - 17:30)

## Day 3
    
- Spatial microsimulation without micro-data (9:30 - 11:30)
    - Methods (MD - 1h)
    - Quality of the microsimulation (MD - 1h)
    
- Adding the household information (11:30 - 13:00)
    - Depending on the databases (MD - 30 min)
    - Several studied cases (MD - 1h00)
    
- Adapt the method to the aim of the simulation (14:00 - 17:00)
    - Choice of data and methods (MD - 30 min)
    - Application to prepared examples or their own data and aims (RL AND MD - 2h30)

- Conclusion to the course (RL 17:00 - 17:30)

